### ISSUE TITLE
Have md-agent use pqa to fill in parameters when applicable

### ISSUE THREAD

**Issue by qcampbel** [ur-whitelab/md-agent#27]
Would be neat feature if we can get paperqa to fill in parameters for openMM setup. Right now, we manually have to type all parameters in our prompt for MRKL to run simulations.

**Comment by SamCox822** [comment]
linking this to the paper-qa issue/PR. we may require some prompting, etc to make this work the way you describe, but in theory, adding pqa as a tool should close this issue
